# Generated by Django 4.2 on 2023-05-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_loans', '0003_pagamento_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
