# Generated by Django 4.2 on 2023-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_loans", "0005_alter_emprestimo_taxa_de_juros"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="valor_devido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
